Unbashify util$ scripts
Also clean them up a bit: remove unneeded redirection to /dev/null,
remove explicite paths for ls, rm etc.

diff --git a/util/check_update b/util/check_update
--- a/util/check_update
+++ b/util/check_update
@@ -1,77 +1,70 @@
-#!/bin/bash
+#!/bin/sh
 #
 #  CHECK_UPDATE -- Check to see if an update is available.  Return $status=1
 #  if a patch is available.
 #
 
+set -e
+
 # Initialize the $iraf and environment.
 if [ -z "$iraf" ]; then
   if [ -e "$HOME/.iraf/setup.sh" ]; then
-    source $HOME/.iraf/setup.sh
+    . "$HOME/.iraf/setup.sh"
   else
-    source unix/hlib/setup.sh
+    . unix/hlib/setup.sh
   fi
 else
-    source $iraf/unix/hlib/setup.sh
+    . "$iraf/unix/hlib/setup.sh"
 fi
 
 
 # Called from Makefile, set iraf root.
-source $iraf/unix/hlib/irafuser.sh
-
-
-REPO=`${iraf}/util/pkgrepo`
-if [ -n $IRAFARCH ]; then
-    arch=$IRAFARCH
-else
-    arch=`${iraf}/unix/hlib/irafarch.sh -actual`
-fi
+. "$iraf/unix/hlib/irafuser.sh"
 
 
 # Check to see if a patch file is available.
 
-/bin/rm -f /tmp/_rdate /tmp/_pdate
+rm -f /tmp/_rdate /tmp/_pdate
 
-FGET="${iraf}/util/fget"
-${FGET} -q -o /tmp/_rdate http://iraf.noao.edu/ftp/v216/PCIX/.release_date
-${FGET} -q -o /tmp/_pdate http://iraf.noao.edu/ftp/v216/PCIX/.patch_release
+FGET="${iraf}util/fget"
+${FGET} -q -o /tmp/_rdate http://iraf.noao.edu/ftp/v216/PCIX/.release_date || true
+${FGET} -q -o /tmp/_pdate http://iraf.noao.edu/ftp/v216/PCIX/.patch_release || true
 
 if [ -e /tmp/_rdate ]; then
-    rdate=`cat /tmp/_rdate`
+    rdate=$(cat /tmp/_rdate)
 else
-    /bin/echo "cannot get rdate"
+    echo "cannot get rdate"
     exit 0
 fi
 if [ -e /tmp/_pdate ]; then
-    pdate=`cat /tmp/_pdate`
+    pdate=$(cat /tmp/_pdate)
 else
     echo "cannot get pdate"
     exit 0
 fi
 
 
-if [ -e ${iraf}/.patch_release ]; then
-    ipdate=`/bin/ls -l --time-style=+%s ${iraf}/.patch_release | awk '{ print ($6) }'`
+if [ -e "${iraf}/.patch_release" ]; then
+    ipdate=$(ls -l --time-style=+%s ${iraf}/.patch_release | awk '{ print ($6) }')
 else
     ipdate=0
 fi
 
-if [ "$1" == "-d" ]; then			# Debug
-  /bin/echo " rdate = " $rdate
-  /bin/echo " pdate = " $pdate
-  /bin/echo "ipdate = " $ipdate
+if [ "$1" = "-d" ]; then			# Debug
+  echo " rdate = $rdate"
+  echo " pdate = $pdate"
+  echo "ipdate = $ipdate"
 fi
 
-if (( $rdate>$pdate )); then			# New Release
+if [ "$rdate" -gt "$pdate" ]; then			# New Release
     exit 1
 fi
 
 
-if (( $pdate==0 )); then
+if [ "$pdate" = 0 ]; then
     exit 0				
-elif (( $pdate>$ipdate && $ipdate!=0 )); then	# Patch newer than installed
+elif [ "$pdate" -gt "$ipdate" ] && [ "$ipdate" != 0 ]; then	# Patch newer than installed
     exit 1
 fi
-
 
 exit 0						# No update available
diff --git a/util/iraf_update b/util/iraf_update
--- a/util/iraf_update
+++ b/util/iraf_update
@@ -1,60 +1,47 @@
-#!/bin/bash
+#!/bin/sh
 #
 #  IRAF_UPDATE - Update the core IRAF system with a cumulative patch.
 
 opt="all"
-all=yes
-src_only=no
-list_only=no
-core_only=no
-noao_only=no
-vo_only=no
 
-if (( $#<1 )); then
+if [ $# -lt 1 ]; then
     opt="all"
-    all=yes
 else
 
     # Process cmdline flags.
     while [ -n "$1" ]; do
       case "$1" in
       "-all")                          # clean all package .s
-          all=yes
 	  opt="all"
 	  ;;
       "-src")                          # update only . code
-          src_only=yes
 	  opt="src"
 	  ;;
       "-list")                         # list files needing updating
-          list_only=yes
 	  opt="list"
 
-	  /bin/echo ""
-	  util/check_update
-	  if (( $?==0 )); then
-	      /bin/echo "IRAF is up to date"
+	  echo ""
+	  
+	  if util/check_update; then
+	      echo "IRAF is up to date"
 	  else
-	      /bin/echo "An IRAF update is available"
+	      echo "An IRAF update is available"
 	  fi
-	  /bin/echo ""
-	  (cd util; ${iraf}/util/pkgupdate -list)
+	  echo
+	  (cd util && "${iraf}/util/pkgupdate" -list)
 	  exit 0
 	  ;;
       "-core")                         # update only core system
-          core_only=yes
 	  opt="core"
 	  ;;
       "-noao")                         # update only NOAO package
-          noao_only=yes
 	  opt="noao"
 	  ;;
       "-vo")                           # update only VO package
-          vo_only=yes
 	  opt="vo"
 	  ;;
       *)
-          /bin/echo "Error: Unknown option '"$1"', quitting."
+          echo "Error: Unknown option '$1', quitting."
           exit 1
       esac
 
@@ -66,44 +53,34 @@ fi
 # Initialize the $iraf and environment.
 if [ -z "$iraf" ]; then
   if [ -e "$HOME/.iraf/setup.sh" ]; then
-    source $HOME/.iraf/setup.sh
+    . "$HOME/.iraf/setup.sh"
   else
-    source unix/hlib/setup.sh
+    . unix/hlib/setup.sh
   fi
 else
-    source $iraf/unix/hlib/setup.sh
+    . "$iraf/unix/hlib/setup.sh"
 fi
 
 
 # Called from Makefile, iraf=true root.
-source $iraf/unix/hlib/irafuser.sh
-irafdir=$iraf
-
-
-REPO=`${irafdir}/util/pkgrepo`
-if [ -n "$IRAFARCH" ]; then
-    arch=$IRAFARCH
-else
-    arch=`${irafdir}/unix/hlib/irafarch.sh -actual`
-fi
-
+. "$iraf/unix/hlib/irafuser.sh"
 
 #  Init the build scripts as the first update.
-#/bin/echo "Updating build scripts ...."
+#echo "Updating build scripts ...."
 #${iraf}/util/self_update
 
 
 #  Execute the update.
-/bin/echo "Updating IRAF system  ...."
+echo "Updating IRAF system  ...."
 util/iraf_latest $opt
+status=$?
 
-if (( $? == 2 )); then
-   /bin/echo -n "Update Status:    No updates necessary"
-else if (( $? == 0 )); then
-   /bin/echo -n "Update Status:    Successful	"
+if [ "$status" = 2 ]; then
+   echo "Update Status:    No updates necessary"
+elif [ "$status" = 0 ]; then
+   echo "Update Status:    Successful"
 else
-   /bin/echo -n "Update Status:    Fails	"
+   echo "Update Status:    Fails"
 fi
-/bin/echo ""
 
 exit 0
diff --git a/util/mkclean b/util/mkclean
--- a/util/mkclean
+++ b/util/mkclean
@@ -1,34 +1,33 @@
-#!/bin/bash
+#!/bin/sh
 #
 #  MKSRC -- Make a pure source tree and configure the links for the 
 #  current architecture.
 
-
-export 	PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/5bin:/usr/ucb:/etc:/usr/etc:$PATH:/usr/local/bin:/opt/local/bin:/local/bin:/home/local/bin
+set -e
 
 # Initialize the $iraf and environment.
 if [ -z "$iraf" ]; then
   if [ -e "$HOME/.iraf/setup.sh" ]; then
-    source $HOME/.iraf/setup.sh
+    . "$HOME/.iraf/setup.sh"
   else
-    source unix/hlib/setup.sh
+    . unix/hlib/setup.sh
   fi
 else
-    source $iraf/unix/hlib/setup.sh
+    . "$iraf/unix/hlib/setup.sh"
 fi
 
 # Utility aliases.
-source $iraf/unix/hlib/util.sh
+. "$iraf/unix/hlib/util.sh"
 
 if [ ! -n "$iraf" ];  then
-    /bin/echo ""
-    /bin/echo "Error:  You must have the iraf env variable defined !"
-    /bin/echo ""
+    echo
+    echo "Error:  You must have the iraf env variable defined !"
+    echo
     exit 1
 fi
 
 exec=yes
-arch=`$iraf/unix/hlib/irafarch.sh`
+arch=$("$iraf/unix/hlib/irafarch.sh")
 
 
 #=============================================================================
@@ -56,56 +55,43 @@ done
 # Determine platform architecture.
 #----------------------------------
 
-mach=`$iraf/unix/hlib/irafarch.sh -actual`
-hmach=`$iraf/unix/hlib/irafarch.sh -actual`
-
-/bin/echo "mach = " $mach
-/bin/echo "hmach = " $hmach
-
-/bin/echo -n "Clean host directories ...."
-if [ $exec == "yes" ]; then
-    /bin/rm -f unix/bin.$arch/[agm-z]*.e unix/bin.$arch/lib[bco]*.a >> /dev/null  2>&1
+echo "Clean '$arch' host directories ...."
+if [ $exec = "yes" ]; then
+    rm -f "unix/bin.$arch/"[agm-z]*.e "unix/bin.$arch/"lib[bco]*.a
 else
-    /bin/ls -l unix/bin.$arch/[agm-z]*.e unix/bin.$arch/lib[bco]*.a
+    ls -l "unix/bin.$arch/"[agm-z]*.e "unix/bin.$arch/"lib[bco]*.a
 fi
-/bin/echo "		Done"
 
-
-/bin/echo -n "Clean src directories ...."
-pats=("local" "math" "pkg" "sys" "noao/[adfimnorst]*")
-for i in ${pats[@]} ; do
-  if [ $exec == "yes" ]; then
-    find $i -type f -name \*.a -exec /bin/rm -f {} \;	>> /dev/null 2>&1
-    find $i -type f -name \*.e -exec /bin/rm -f {} \;	>> /dev/null 2>&1
-    find $i -type f -name \*.o -exec /bin/rm -f {} \;	>> /dev/null 2>&1
+echo "Clean src directories ...."
+pats="local math pkg sys noao/[adfimnorst]*"
+for i in $pats ; do
+  if [ $exec = "yes" ]; then
+    find "$i" -type f -name \*.a -exec rm -f {} \;
+    find "$i" -type f -name \*.e -exec rm -f {} \;
+    find "$i" -type f -name \*.o -exec rm -f {} \;
   else
-    find $i -type f -name \*.a -exec /bin/ls -l {} \;
-    find $i -type f -name \*.e -exec /bin/ls -l {} \;
-    find $i -type f -name \*.o -exec /bin/ls -l {} \;
+    find "$i" -type f -name \*.a -exec ls -l {} \;
+    find "$i" -type f -name \*.e -exec ls -l {} \;
+    find "$i" -type f -name \*.o -exec ls -l {} \;
   fi
 done
-/bin/echo "		Done"
 
-
-/bin/echo -n "Clean '$arch' bin directories ...."
-if [ $exec == "yes" ]; then
-    /bin/rm -rf bin.$arch/lib[a-z]*.a 			>> /dev/null 2>&1
-    /bin/rm -rf bin.$arch/*.[eoZ] 			>> /dev/null 2>&1
-    /bin/rm -rf noao/bin.$arch/*.[aeoZ] 		>> /dev/null 2>&1
+echo "Clean '$arch' bin directories ...."
+if [ $exec = "yes" ]; then
+    rm -rf "bin.$arch/"lib[a-z]*.a
+    rm -rf "bin.$arch/"*.[eoZ]
+    rm -rf "noao/bin.$arch/"*.[aeoZ]
 else
-    /bin/ls -l  bin.$arch/lib[a-z]*.a 			>> /dev/null 2>&1
-    /bin/ls -l  bin.$arch/*.[aeoZ] 			>> /dev/null 2>&1
-    /bin/ls -l  noao/bin.$arch/*.[aeoZ] 		>> /dev/null 2>&1
+    ls -l  "bin.$arch/"lib[a-z]*.a
+    ls -l  "bin.$arch/"*.[aeoZ]
+    ls -l  "noao/bin.$arch/"*.[aeoZ]
 fi
-/bin/echo "		Done"
 
-
-/bin/echo -n "Cleaning spool files ...."
-if [ $exec == "yes" ]; then
-    find . -name spool\* -print -exec /bin/rm -f {} \;	>> /dev/null 2>&1
+echo "Cleaning spool files ...."
+if [ $exec = "yes" ]; then
+    find . -name spool\* -print -exec rm -f {} \;
 else
-    find . -name spool\* -print 
+    find . -name spool\* -exec ls -l {} \;
 fi
-/bin/echo "		Done"
 
 exit 0
diff --git a/util/mksrc b/util/mksrc
--- a/util/mksrc
+++ b/util/mksrc
@@ -1,35 +1,34 @@
-#!/bin/bash
+#!/bin/sh
 #
 #  MKSRC -- Make a pure source tree and configure the links for the 
 #  current architecture.
 
+set -e
 
 # Initialize the $iraf and environment.
 if [ -z "$iraf" ]; then
   if [ -e "$HOME/.iraf/setup.sh" ]; then
-    source $HOME/.iraf/setup.sh
+    . "$HOME/.iraf/setup.sh"
   else
-    source unix/hlib/setup.sh
+    . unix/hlib/setup.sh
   fi
 else
-    source $iraf/unix/hlib/setup.sh
+    . "$iraf/unix/hlib/setup.sh"
 fi
 
 
 # Utility aliases.
-source $iraf/unix/hlib/util.sh
+. "$iraf/unix/hlib/util.sh"
 
 if [ -z "$iraf" ]; then
-    /bin/echo ""
-    /bin/echo "Error:  You must have the iraf env variable defined !"
-    /bin/echo ""
+    echo
+    echo "Error:  You must have the iraf env variable defined !"
+    echo
     exit 1
 fi
 
 
 exec=yes
-arch=`$iraf/unix/hlib/irafarch.sh`
-
 
 #=============================================================================
 # Process any command line arguments.
@@ -57,49 +56,44 @@ done
 # Determine platform architecture.
 #----------------------------------
 
-/bin/echo -n "Clean host directories ...."
-  if [ $exec == "yes" ]; then
-    /bin/rm -f unix/bin.*/*.e unix/bin.*/lib*.a >> /dev/null 2>&1
+echo "Clean host directories ...."
+  if [ $exec = "yes" ]; then
+    rm -f unix/bin.*/*.e unix/bin.*/lib*.a
   else
-    /bin/ls -l unix/bin.*/*.e unix/bin.*/lib*.a
+    ls -l unix/bin.*/*.e unix/bin.*/lib*.a
   fi
-/bin/echo "		Done"
 
 
-
-/bin/echo -n "Clean src directories ...."
-dirs=("local" "math" "pkg" "sys" "noao")
-for i in ${dirs[@]}; do
-  if [ $exec == "yes" ]; then
-    find $i -type f -name \*.a   -exec /bin/rm -f {} \;	    >> /dev/null 2>&1
-    find $i -type f -name \*.e   -exec /bin/rm -f {} \;	    >> /dev/null 2>&1
-    find $i -type f -name \*.o   -exec /bin/rm -f {} \;	    >> /dev/null 2>&1
-    find $i -type f -name OBJS\* -exec /bin/ls -l {} \;	    >> /dev/null 2>&1
+echo "Clean src directories ...."
+dirs="local math pkg sys noao"
+for i in $dirs; do
+  if [ $exec = "yes" ]; then
+    find "$i" -type f -name \*.a   -exec rm -f {} \;
+    find "$i" -type f -name \*.e   -exec rm -f {} \;
+    find "$i" -type f -name \*.o   -exec rm -f {} \;
+    find "$i" -type f -name OBJS\* -exec ls -l {} \;
   else
-    find $i -type f -name \*.a   -exec /bin/ls -l {} \;
-    find $i -type f -name \*.e   -exec /bin/ls -l {} \;
-    find $i -type f -name \*.o   -exec /bin/ls -l {} \;
-    find $i -type f -name OBJS\* -exec /bin/ls -l {} \;
+    find "$i" -type f -name \*.a   -exec ls -l {} \;
+    find "$i" -type f -name \*.e   -exec ls -l {} \;
+    find "$i" -type f -name \*.o   -exec ls -l {} \;
+    find "$i" -type f -name OBJS\* -exec ls -l {} \;
   fi
 done
-/bin/echo "		Done"
 
 
-/bin/echo -n "Clean bin directories ...."
-if [ $exec == "yes" ]; then
-    /bin/rm -rf bin.*/*.[aeoZ] noao/bin.*/*.[aeoZ] OBJS*    >>/dev/null 2>&1
+echo "Clean bin directories ...."
+if [ $exec = "yes" ]; then
+    rm -rf bin.*/*.[aeoZ] noao/bin.*/*.[aeoZ] OBJS*
 else
-    /bin/ls -l  bin.*/*.[aeoZ] noao/bin.*/*.[aeoZ] OBJS*
+    ls -l  bin.*/*.[aeoZ] noao/bin.*/*.[aeoZ] OBJS*
 fi
-/bin/echo "		Done"
 
 
-/bin/echo -n "Cleaning spool files ...."
-if [ $exec == "yes" ]; then
-    find . -name spool\* -print -exec /bin/rm -f {} \;	    >> /dev/null 2>&1
-    find . -name _spool\* -print -exec /bin/rm -f {} \;	    >> /dev/null 2>&1
+echo "Cleaning spool files ...."
+if [ $exec = "yes" ]; then
+    find . -name spool\* -print -exec rm -f {} \;
+    find . -name _spool\* -print -exec rm -f {} \;
 else
-    find . -name spool\* -print
-    find . -name _spool\* -print
+    find . -name spool\* -exec ls {} \;
+    find . -name _spool\* -exec ls {} \;
 fi
-/bin/echo "		Done"
diff --git a/util/pkginit b/util/pkginit
--- a/util/pkginit
+++ b/util/pkginit
@@ -1,37 +1,37 @@
-#!/bin/bash
+#!/bin/sh
 #
 #  PKGINIT - Initialize the dynamic package directory by fetching the most
 #  recent repository definition files.
 
-bindir="`dirname $0`"                # get iraf root directory 
+bindir="$(dirname "$0")"                # get iraf root directory 
 irafdir=${bindir%/*}
 
 # Initialize the $iraf and environment.
 if [ -z "$iraf" ]; then
   if [ -e "$HOME/.iraf/setup.sh" ]; then
-    source $HOME/.iraf/setup.sh
+    . "$HOME/.iraf/setup.sh"
   else
-    source ../unix/hlib/setup.sh
+    . ../unix/hlib/setup.sh
   fi
 else
-    source $iraf/unix/hlib/setup.sh
+    . "$iraf/unix/hlib/setup.sh"
 fi
 
 
-REPO=`${irafdir}/util/pkgrepo`			# get repo url
+REPO=$("${irafdir}/util/pkgrepo")			# get repo url
 man=".repo_manifest"
-arch=`${irafdir}/unix/hlib/irafarch.sh -actual`
+arch=$("${irafdir}/unix/hlib/irafarch.sh" -actual)
 
 
-$irafdir/util/pkgget ${REPO}/REPO.MANIFEST  .repo_manifest
-if (( $?>0 )); then
-    /bin/echo "Cannot download repository manifest file, quitting."
+"$irafdir/util/pkgget" "${REPO}/REPO.MANIFEST"  .repo_manifest
+if [ $? -gt 0 ]; then
+    echo "Cannot download repository manifest file, quitting."
     exit $?
 fi
 
-$irafdir/util/pkgget ${REPO}/REPO.DESC 	    .repo_desc
-if (( $?>1 )); then
-    /bin/echo "Cannot download repository description file, quitting."
+"$irafdir/util/pkgget" "${REPO}/REPO.DESC" 	    .repo_desc
+if [ $? -gt 1 ]; then
+    echo "Cannot download repository description file, quitting."
     exit $?
 fi
 
@@ -42,11 +42,11 @@ fi
 # architectures so don't filter by the current architecture.
 
 if [ -n "$IRAFARCH" ]; then
-    cat $man | egrep -v "^#" | awk '{printf("%s\n", $2)}' | uniq  >  .repo_pkgs
-    cat $man    			 	        	  >  .repo_local
+    cat "$man" | grep -v "^#" | awk '{printf("%s\n", $2)}' | uniq  >  .repo_pkgs
+    cat "$man"							   >  .repo_local
 else
-    cat $man | grep "${arch}\ " | awk '{printf("%s\n", $2)}' 	  >  .repo_pkgs
-    cat $man | grep "${arch}\ " 			 	  >  .repo_local
+    cat "$man" | grep "${arch}\ " | awk '{printf("%s\n", $2)}'     >  .repo_pkgs
+    cat "$man" | grep "${arch}\ " 			 	   >  .repo_local
 fi
 
 
