IRAF PCIX Version 2.16.1

diff --git a/util/iraf_latest b/util/iraf_latest
--- a/util/iraf_latest
+++ b/util/iraf_latest
@@ -1,84 +1,114 @@
-#!/bin/csh -f
+#!/bin/bash
 #
 #  IRAF_LATEST - Update the system with the latest distribution files.
 
-unalias 	grep ls
 
-set opt		= "all"
+opt="all"
 
 
-if ($#argv < 1) then
-    echo "Usage:  iraf_latest <opt>"
+if (( $#<1 )); then
+    /bin/echo "Usage:  iraf_latest <opt>"
     exit 0
 else
-    set opt = $1
-endif
+    opt=$1
+fi
+
+# Initialize the $iraf and environment.
+if [ -z "$iraf" ]; then
+  if [ -e "$HOME/.iraf/setup.sh" ]; then
+    source $HOME/.iraf/setup.sh
+  else
+    source unix/hlib/setup.sh
+  fi
+else
+    source $iraf/unix/hlib/setup.sh
+fi
 
 
 # Called from Makefile, set iraf root.
-set  iraf       = $cwd/			
-source $iraf/unix/hlib/irafuser.csh
+if [ -e $iraf/unix/hlib/irafuser.sh ]; then
+    source $iraf/unix/hlib/irafuser.sh
+fi
+
+echo '$iraf is '$iraf
 
 
-set REPO	= `${iraf}/util/pkgrepo`
-if ($?IRAFARCH) then
-    set arch    = $IRAFARCH
+REPO=`${iraf}/util/pkgrepo`
+if [ -n "$IRAFARCH" ]; then
+    arch=$IRAFARCH
 else
-    set arch    = `${iraf}/unix/hlib/irafarch.csh -actual`
-endif
+    arch=`${iraf}/unix/hlib/irafarch.sh -actual`
+fi
 
 
-echo "iraf_latest: cwd = " $cwd
+#/bin/echo "iraf_latest: cwd = " `pwd`
 
 # Figure out which binaries are required.
-set files = "patch-src.tar.gz"			# always need the source ....
-set bins = ""
-foreach b (linux linux64 macosx macintel)
-    if (-e "bin.$b/x_images.e") then
-	set bins = `echo $bins " " $b`
-	switch ($b)
-	case linux:
-	    set files = `echo "$files patch.lnux.x86.tar.gz"`
-	    breaksw
-	case linux64:
-	    set files = `echo "$files patch.lnux.x86_64.tar.gz"`
-	    breaksw
-	case macosx:
-	    set files = `echo "$files patch.macx.uni.tar.gz"`
-	    breaksw
-	case macintel:
-	    set files = `echo "$files patch.macx.x86_64.tar.gz"`
-	    breaksw
-	endsw
-    endif
-end
-echo "Updating binaries:  " $bins
+files="patch-src.tar.gz"			# always need the source ....
+bins=""
+archs=("linux" "linux64" "macosx" "macintel")
+for b in ${archs[@]} ; do
+    if [ -e "bin.$b/x_images.e" ]; then
+	bins=`/bin/echo $bins " " $b`
+	case "$b" in
+	"linux")
+	    files=`/bin/echo "$files patch.lnux.x86.tar.gz"`
+	    ;;
+	"linux64")
+	    files=`/bin/echo "$files patch.lnux.x86_64.tar.gz"`
+	    ;;
+	"macosx")
+	    files=`/bin/echo "$files patch.macx.x86.tar.gz"`
+	    ;;
+	"macintel")
+	    files=`/bin/echo "$files patch.macx.x86_64.tar.gz"`
+	    ;;
+	esac
+    fi
+done
+/bin/echo "Updating binaries:  " $bins
 
 
 # Download the needed files to /tmp
 
-set FGET        = "${iraf}/util/fget"
-set REPO	= `util/pkgrepo`
-foreach f ($files)
-    echo -n "Downloading: $f"
+FGET="${iraf}/util/fget"
+REPO=`${iraf}/util/pkgrepo`
+for f in ${files[@]} ; do
+    /bin/echo -n "Downloading: $f"
     ${FGET} -q -d /tmp/ $REPO/$f
 
-    echo -n " Unpacking ..."
+    if [ ! -e /tmp/$f ]; then
+	/bin/echo ""
+	/bin/echo "Error: file $REPO/$f not found, quitting"
+	exit 1
+    elif [ -z /tmp/$f ]; then
+	/bin/echo ""
+	/bin/echo "Error downloading $REPO/$f, quitting"
+	exit 1
+    fi
+
+    /bin/echo ""
+    /bin/echo -n "Unpacking ..."
     tar zxf /tmp/$f
     /bin/rm -f /tmp/$f
 
-    echo    " Done."
-end
+    /bin/echo    " Done."
+done
 
 
 #  For the initial release, the update procedures haven't yet been defined.
 #  This script will be replaced by the working version at the first release.
 
 
-if ($opt == "all") then				# Update everything
-    echo "Update all external packages ..."
-    (chdir extern ; make update)
-endif
+if [ $opt == "all" ]; then			# Update everything
+  if [ -e extern/.installed ]; then
+    /bin/echo "Update all external packages ..."
+    (cd extern ; make update)
+  fi
+else
+    /bin/echo "Unknown option '"$opt"'"
+    exit 1
+fi
 
-echo ""
+/bin/echo ""
 exit 0
diff --git a/util/iraf_update b/util/iraf_update
--- a/util/iraf_update
+++ b/util/iraf_update
@@ -1,100 +1,109 @@
-#!/bin/csh -f
+#!/bin/bash
 #
 #  IRAF_UPDATE - Update the core IRAF system with a cumulative patch.
 
-unalias 	grep ls
+opt="all"
+all=yes
+src_only=no
+list_only=no
+core_only=no
+noao_only=no
+vo_only=no
 
-set opt		= "all"
-set all		= yes
-set src_only	= no
-set list_only	= no
-set core_only	= no
-set noao_only	= no
-set vo_only	= no
-
-if ($#argv < 1) then
-    set opt	= "all"
-    set all	= yes
+if (( $#<1 )); then
+    opt="all"
+    all=yes
 else
 
     # Process cmdline flags.
-    while ("$1" != "")
-      switch ("$1")
-      case -all:                          # clean all package sources
-        set all = yes
-	set opt	 = "all"
-        breaksw
-      case -src:                          # update only source code
-        set src_only = yes
-	set opt	 = "src"
-        breaksw
-      case -list:                         # list files needing updating
-        set list_only = yes
-	set opt	 = "list"
+    while [ -n "$1" ]; do
+      case "$1" in
+      "-all")                          # clean all package .s
+          all=yes
+	  opt="all"
+	  ;;
+      "-src")                          # update only . code
+          src_only=yes
+	  opt="src"
+	  ;;
+      "-list")                         # list files needing updating
+          list_only=yes
+	  opt="list"
 
-	echo ""
-	util/check_update
-	if ($status == 0) then
-	    echo "IRAF is up to date"
-	else
-	    echo "An IRAF update is available"
-	endif
-	echo ""
-	(chdir util ; ${iraf}/util/pkgupdate -list)
-	exit 0
-
-      case -core:                         # update only core system
-        set core_only = yes
-	set opt	 = "core"
-        breaksw
-      case -noao:                         # update only NOAO package
-        set noao_only = yes
-	set opt	 = "noao"
-        breaksw
-      case -vo:                           # update only VO package
-        set vo_only = yes
-	set opt	 = "vo"
-        breaksw
-      default:
-        echo "Error: Unknown option '"$1"', quitting."
-        exit 1
-      endsw
+	  /bin/echo ""
+	  util/check_update
+	  if (( $?==0 )); then
+	      /bin/echo "IRAF is up to date"
+	  else
+	      /bin/echo "An IRAF update is available"
+	  fi
+	  /bin/echo ""
+	  (cd util; ${iraf}/util/pkgupdate -list)
+	  exit 0
+	  ;;
+      "-core")                         # update only core system
+          core_only=yes
+	  opt="core"
+	  ;;
+      "-noao")                         # update only NOAO package
+          noao_only=yes
+	  opt="noao"
+	  ;;
+      "-vo")                           # update only VO package
+          vo_only=yes
+	  opt="vo"
+	  ;;
+      *)
+          /bin/echo "Error: Unknown option '"$1"', quitting."
+          exit 1
+      esac
 
       shift
-   end
-endif
+   done
+fi
 
 
-# Called from Makefile, set iraf root.
-set  iraf       = $cwd/			
-source $iraf/unix/hlib/irafuser.csh
-set  irafdir    = $iraf
-
-
-set REPO	= `${irafdir}/util/pkgrepo`
-if ($?IRAFARCH) then
-    set arch    = $IRAFARCH
+# Initialize the $iraf and environment.
+if [ -z "$iraf" ]; then
+  if [ -e "$HOME/.iraf/setup.sh" ]; then
+    source $HOME/.iraf/setup.sh
+  else
+    source unix/hlib/setup.sh
+  fi
 else
-    set arch    = `${irafdir}/unix/hlib/irafarch.csh -actual`
-endif
+    source $iraf/unix/hlib/setup.sh
+fi
+
+
+# Called from Makefile, iraf=true root.
+source $iraf/unix/hlib/irafuser.sh
+irafdir=$iraf
+
+
+REPO=`${irafdir}/util/pkgrepo`
+if [ -n "$IRAFARCH" ]; then
+    arch=$IRAFARCH
+else
+    arch=`${irafdir}/unix/hlib/irafarch.sh -actual`
+fi
 
 
 #  Init the build scripts as the first update.
-#echo "Updating build scripts ...."
-util/self_update
+#/bin/echo "Updating build scripts ...."
+#${iraf}/util/self_update
 
 
 #  Execute the update.
-echo "Updating IRAF system  ...."
+/bin/echo "Updating IRAF system  ...."
 util/iraf_latest $opt
 
-if ($status == 2) then
-   echo -n "Update Status:    No updates necessary"
-else if ($status == 0) then
-   echo -n "Update Status:    Successful	"
+if (( $? == 2 )); then
+   /bin/echo -n "Update Status:    No updates necessary"
+else if (( $? == 0 )); then
+   /bin/echo -n "Update Status:    Successful	"
 else
-   echo -n "Update Status:    Fails	"
-endif
-echo ""
+   /bin/echo -n "Update Status:    Fails	"
+fi
+/bin/echo ""
 
 exit 0
diff --git a/util/mksysgen b/util/mksysgen
--- a/util/mksysgen
+++ b/util/mksysgen
@@ -1,45 +1,79 @@
-#!/bin/csh -f
+#!/bin/bash
 #
 
-if (! $?iraf) then
-    #echo ""
-    #echo "Error:  You must have the iraf env variable defined !"
-    #echo ""
+# Initialize the $iraf and environment.
+if [ -z "$iraf" ]; then
+  if [ -e "$HOME/.iraf/setup.sh" ]; then
+    source $HOME/.iraf/setup.sh
+  else
+    source unix/hlib/setup.sh
+  fi
+else
+    source $iraf/unix/hlib/setup.sh
+fi
+
+
+if [ -z "$iraf" ]; then
+    #/bin/echo ""
+    #/bin/echo "Error:  You must have the iraf env variable defined !"
+    #/bin/echo ""
     #exit 1
 
-    set  iraf 	= $cwd/
-endif
+    iraf=`pwd`/
+fi
 
+if [ -e "$HOME/.iraf/arch" ]; then
+  if [ -n "$IRAFARCH" ]; then
+    iarch=`cat $HOME/.iraf/arch`
+    if [ "$iarch" != "$IRAFARCH" ]; then
+      /bin/echo ""
+      /bin/echo 'Error:  Your $IRAFARCH does not match $HOME/.iraf/arch,'
+      /bin/echo '        Please change $IRAFARCH or rerun install script.'
+      /bin/echo ""
+      exit 1
+    fi
+  fi
+fi
 
-set  c_start	= `date`
+c_start=`date`
 /bin/rm -f spool */spool
 
 
 $iraf/util/mkclean				# clean old binaries
 
 cd $iraf/unix					# NOVOS bootstrap
-source hlib/irafuser.csh
-sh -x mkpkg.sh |& tee -a spool
+source hlib/irafuser.sh
+sh -x mkpkg.sh 2>&1 | tee -a spool
 
 cd $iraf/					# build NOVOS
-mkpkg |& tee -a spool
+mkpkg 2>&1 | tee -a spool
 
 cd $iraf/unix					# VOS bootstrap
-source hlib/irafuser.csh
-sh -x mkpkg.sh |& tee -a spool
+source hlib/irafuser.sh
+sh -x mkpkg.sh 2>&1 | tee -a spool
+
+cd $iraf/vendor					# build vendor libs
+make all 2>&1 | tee -a ../spool.final
+cd ../
 
 cd $iraf/					# build core system
-mkpkg |& tee -a spool
+mkpkg 2>&1 | tee -a spool
 
 cd $iraf/noao					# build NOAO package
-setenv noao $cwd/
-mkpkg -p noao |& tee -a spool
+export noao=`pwd`/
+mkpkg -p noao 2>&1 | tee -a ../spool.final
 
-set  c_end	= `date`
+cd $iraf/vo					# build NOAO package
+export vo=`pwd`/
+mkpkg -p vo 2>&1 | tee -a ../spool.final
+
+/bin/rm -rf bin*/pkgconfig			# misc clean up
+
+c_end=`date`
 
 
-echo ""
-echo ""
-echo ""
-echo "Start:  $c_start"
-echo "  End:  $c_end"
+/bin/echo ""
+/bin/echo ""
+/bin/echo ""
+/bin/echo "Start:  $c_start"
+/bin/echo "  End:  $c_end"
diff --git a/util/pkginit b/util/pkginit
--- a/util/pkginit
+++ b/util/pkginit
@@ -1,29 +1,39 @@
-#!/bin/csh -f
+#!/bin/bash
 #
 #  PKGINIT - Initialize the dynamic package directory by fetching the most
 #  recent repository definition files.
 
-unalias 	grep
+bindir="`dirname $0`"                # get iraf root directory 
+irafdir=${bindir%/*}
 
-set  bindir     = "`dirname $0`"                # get iraf root directory 
-set  irafdir    = $bindir:h
+# Initialize the $iraf and environment.
+if [ -z "$iraf" ]; then
+  if [ -e "$HOME/.iraf/setup.sh" ]; then
+    source $HOME/.iraf/setup.sh
+  else
+    source ../unix/hlib/setup.sh
+  fi
+else
+    source $iraf/unix/hlib/setup.sh
+fi
 
-set  REPO	= `${irafdir}/util/pkgrepo`	# get repo url
-set  man 	= ".repo_manifest"
-set  arch	= `${irafdir}/unix/hlib/irafarch.csh -actual`
+
+REPO=`${irafdir}/util/pkgrepo`			# get repo url
+man=".repo_manifest"
+arch=`${irafdir}/unix/hlib/irafarch.sh -actual`
 
 
 $irafdir/util/pkgget ${REPO}/REPO.MANIFEST  .repo_manifest
-if ($status == 1) then
-    echo "Cannot download repository manifest file, quitting."
-    exit $status
-endif
+if (( $?>0 )); then
+    /bin/echo "Cannot download repository manifest file, quitting."
+    exit $?
+fi
 
 $irafdir/util/pkgget ${REPO}/REPO.DESC 	    .repo_desc
-if ($status == 1) then
-    echo "Cannot download repository description file, quitting."
-    exit $status
-endif
+if (( $?>1 )); then
+    /bin/echo "Cannot download repository description file, quitting."
+    exit $?
+fi
 
 
 # Create a list of packages available for the current platform.  We pull
@@ -31,13 +41,13 @@ endif
 # IRAFARCH defined, assumed we're interested in managing multiple
 # architectures so don't filter by the current architecture.
 
-if ($?IRAFARCH) then
+if [ -n "$IRAFARCH" ]; then
     cat $man | egrep -v "^#" | awk '{printf("%s\n", $2)}' | uniq  >  .repo_pkgs
     cat $man    			 	        	  >  .repo_local
 else
     cat $man | grep "${arch}\ " | awk '{printf("%s\n", $2)}' 	  >  .repo_pkgs
     cat $man | grep "${arch}\ " 			 	  >  .repo_local
-endif
+fi
 
 
 exit 0
diff --git a/util/pkginst b/util/pkginst
--- a/util/pkginst
+++ b/util/pkginst
@@ -1,86 +1,97 @@
-#!/bin/csh -f
+#!/bin/bash
 #
 #  PKGINST - Install the named package.
 
-unalias 	grep sort uniq ls awk
-
-if ($#argv < 1) then
+if (( $#<1 )); then
     exit 0
 else
-    set pkg = $1
-endif
+    pkg=$1
+fi
 
-set  bindir     = "`dirname $0`"                # get iraf root directory 
-set  irafdir    = $bindir:h
+bindir="`dirname $0`"                # get iraf root directory 
+irafdir=${bindir%/*}
 
-set  REPO	= `${irafdir}/util/pkgrepo`
-if ($?IRAFARCH) then
-    set arch    = $IRAFARCH
+# Initialize the $iraf and environment.
+if [ -z "$iraf" ]; then
+  if [ -e "$HOME/.iraf/setup.sh" ]; then
+    source $HOME/.iraf/setup.sh
+  else
+    source ../unix/hlib/setup.sh
+  fi
 else
-    set arch    = `${irafdir}/unix/hlib/irafarch.csh -actual`
-endif
+    source $iraf/unix/hlib/setup.sh
+fi
 
-echo "Setting architecture: '$arch' .... "
+
+REPO=`${irafdir}/util/pkgrepo`
+if [ -n "$IRAFARCH" ]; then
+    arch=$IRAFARCH
+else
+    arch=`${irafdir}/unix/hlib/irafarch.sh -actual`
+fi
+
+/bin/echo "Setting architecture: '$arch' .... "
  
 
 # Get any dependency package names.
-set deps=`grep ^$pkg .repo_desc | awk '{printf("%s\n",$2)}' | sed -e 's/,/ /g'`
-set pkg_dep = ""
-foreach d ( $deps )
-   if ("$d" != "none") then
-      echo "Adding dependency '$d' ...."
-      set pkg_dep = "$pkg_dep $d"
-   endif
-end
+deps=`grep ^$pkg .repo_desc | awk '{printf("%s\n",$2)}' | sed -e 's/,/ /g'`
+pkg_dep=""
+for d in ${deps[@]}; do 
+   if [ "$d" != "none" ]; then
+      /bin/echo "Adding dependency '$d' ...."
+      pkg_dep="$pkg_dep $d"
+   fi
+done
 
 # Make a unique list of package, i.e. remove multiple instances of a package.
 #   [Note:  Not used, the manifest should have this already. ]
-set list = `echo $pkg_dep $pkg|awk 'BEGIN {RS=" |\n";}{print $1;}'|sort|uniq`
+list=`/bin/echo $pkg_dep $pkg|awk 'BEGIN {RS=" |\n";}{print $1;}'|sort|uniq`
 
 # Process the requested package and any dependencies.
-foreach ip ($pkg_dep $pkg)
+dep=("$pkg_dep" "$pkg")
+for ip in ${dep[@]}; do
 
-  set pfile = `grep \ $ip\  .repo_manifest | grep ${arch}\  | head -1 | awk '{printf("%s\n",$4)}'`
+  pfile=`grep \ $ip\  .repo_manifest | grep ${arch}\  | head -1 | awk '{printf("%s\n",$4)}'`
 
-  echo $pfile | grep src.tar.gz  > /dev/null
-  if ($status == 0) then
-    set src_only = 1
+  /bin/echo $pfile | grep src.tar.gz  >> /dev/null 2>&1
+  if (( $?==0 )); then
+    src_only=1
   else
-    set src_only = 0
-  endif
+    src_only=0
+  fi
 
   # Remove an existing package file.
-  if (-e $pfile) then
+  if [ -e $pfile ]; then
     /bin/rm -f $pfile
-  endif
+  fi
 
   # Download the repo file and unpack it.
-  echo -n "Installing package '$ip' .... "
+  /bin/echo -n "Installing package '$ip' .... "
   ${irafdir}/util/pkgget ${REPO}/$pfile
-  if ($status == 1) then
-    echo    " [Error]"
-    exit $status
-  endif
+  if (( $?>0 )); then
+    /bin/echo    " [Error]"
+    exit $?
+  fi
 
-  if (-e $pfile) then
+  if [ -e $pfile ]; then
 
     tar zxf $pfile
     /bin/rm -f $pfile
-    echo `date +%s`"  " ${ip}.${arch} > $ip/.installed.${arch}
-    echo `date +%s`"  " $ip > $ip/.installed	
+    /bin/echo `date +%s`"  " ${ip}.${arch} > $ip/.installed.${arch}
+    /bin/echo `date +%s`"  " $ip > $ip/.installed	
 
-    if ($src_only == 1) then
-      echo    " [SOURCE ONLY]"
-      echo `date +%s`"  " $ip > $ip/.src_only
+    if (( $src_only>0 )); then
+      /bin/echo    " [SOURCE ONLY]"
+      /bin/echo `date +%s`"  " $ip > $ip/.src_only
     else
-      echo    " [OK]"
-    endif
+      /bin/echo    " [OK]"
+    fi
   else
-    echo    " [Error]"
-  endif
+    /bin/echo    " [Error]"
+  fi
 
   ${irafdir}/util/pkgenv -init
 
-end
+done
 
 exit 0
